mode: 'rule'
ipv6: true
bind-address: "*"
geodata-mode: true
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country-without-asn.mmdb"
  asn: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country-asn.mmdb"
geo-auto-update: true
geo-update-interval: 24
tun:
  enable: true
  stack: 'gvisor'
  dns-hijack:   
    - 'any:53'
    - 'tcp://any:53'
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
dns:
  enable: true
  ipv6: true
  prefer-h3: false
  respect-rules: true
  use-hosts: true
  use-system-hosts: true
  listen: '0.0.0.0:5335'
  enhanced-mode: 'fake-ip'
  fake-ip-range: '198.18.0.1/16'
  fake-ip-filter-mode: 'blacklist'
  fake-ip-filter:
    - '*.n.n.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
    - 'WORKGROUP'
    - '*.lan'
    - '*.local'
    - 'stun.*.*.*'
    - 'stun.*.*'
    - 'time.windows.com'
    - 'time.nist.gov'
    - 'time.apple.com'
    - 'time.asia.apple.com'
    - '*.ntp.org.cn'
    - '*.openwrt.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'time.ustc.edu.cn'
    - 'pool.ntp.org'
    - 'ntp.ubuntu.com'
    - '*.*.xboxlive.com'
    - 'speedtest.cros.wr.pvp.net'
    - 'ntp.aliyun.com'
    - 'ntp1.aliyun.com'
    - 'ntp2.aliyun.com'
    - 'ntp3.aliyun.com'
    - 'ntp4.aliyun.com'
    - 'ntp5.aliyun.com'
    - 'ntp6.aliyun.com'
    - 'ntp7.aliyun.com'
    - 'time1.aliyun.com'
    - 'time2.aliyun.com'
    - 'time3.aliyun.com'
    - 'time4.aliyun.com'
    - 'time5.aliyun.com'
    - 'time6.aliyun.com'
    - 'time7.aliyun.com'
    - '*.time.edu.cn'
    - 'time1.apple.com'
    - 'time2.apple.com'
    - 'time3.apple.com'
    - 'time4.apple.com'
    - 'time5.apple.com'
    - 'time6.apple.com'
    - 'time7.apple.com'
    - 'time1.google.com'
    - 'time2.google.com'
    - 'time3.google.com'
    - 'time4.google.com'
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - 'music.migu.cn'
    - 'localhost.ptlogin2.qq.com'
    - '*.*.*.srv.nintendo.net'
    - '*.*.stun.playstation.net'
    - '*.ipv6.microsoft.com'
  default-nameserver:
    - '223.6.6.6'
    - '119.28.28.28'
    - '223.5.5.5'
    - '119.29.29.29'
  nameserver:
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'
  proxy-server-nameserver:
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'
  direct-nameserver:
    - '223.6.6.6'
    - '119.28.28.28'
  direct-nameserver-follow-policy: true
  fallback:
    - 'https://cloudflare-dns.com/dns-query'
    - 'https://dns.google/dns-query'
  fallback-filter:
    geoip: true
    geoip-code: 'CN'
    geosite:
      - gfw
    ipcidr:
      - '240.0.0.0/4'
      - '0.0.0.0/32'
      - '127.0.0.1/8'
    domain:
      - '+.google.com'
      - '+.youtube.com'
      - '+.github.com'
  nameserver-policy:
    'software.tongji.edu.cn':
      - '202.120.190.208'
    '+.126.com':
      - '119.29.29.29'
    '+.126.net':
      - '119.29.29.29'
    '+.127.net':
      - '119.29.29.29'
    '+.163.com':
      - '119.29.29.29'
    '+.alibaba.com':
      - '223.5.5.5'
    '+.alicdn.com':
      - '223.5.5.5'
    '+.alipay.com':
      - '223.5.5.5'
    '+.aliyun.com':
      - '223.5.5.5'
    '+.baidu.com':
      - '223.5.5.5'
    '+.bdstatic.com':
      - '223.5.5.5'
    '+.bilibili.com':
      - '119.29.29.29'
    '+.bilivideo.+':
      - '119.29.29.29'
    '+.douyin.com':
      - '180.184.1.1'
    '+.douyincdn.com':
      - '180.184.1.1'
    '+.douyinpic.com':
      - '180.184.1.1'
    '+.douyinvod.com':
      - '180.184.1.1'
    '+.feishu.cn':
      - '180.184.1.1'
    '+.hdslb.com':
      - '119.29.29.29'
    '+.iqiyi.com':
      - '119.29.29.29'
    '+.jd.com':
      - '119.29.29.29'
    '+.netease.com':
      - '119.29.29.29'
    '+.qpic.cn':
      - '119.29.29.29'
    '+.qq.com':
      - '119.29.29.29'
    '+.taobao.com':
      - '223.5.5.5'
    '+.tencent.com':
      - '119.29.29.29'
    '+.tmall.com':
      - '223.5.5.5'
    '+.weixin.com':
      - '119.29.29.29'
    "geosite:steam@cn":
      - '119.29.29.29'
      - '223.5.5.5.5'
    "geosite:category-games@cn":
      - '119.29.29.29'
      - '223.5.5.5.5'
    "+.githubusercontent.com":
      - 'https://cloudflare-dns.com/dns-query'
      - 'https://dns.google/dns-query'
    "+.github.com":
      - 'https://cloudflare-dns.com/dns-query'
      - 'https://dns.google/dns-query'
    "geosite:google":
      - 'https://cloudflare-dns.com/dns-query'
      - 'https://dns.google/dns-query'
    "geosite:gfw":
      - 'https://cloudflare-dns.com/dns-query'
      - 'https://dns.google/dns-query'
    # 自定义直连域名使用国内 dns
    "geosite:cn":
      - '119.29.29.29'
      - '223.5.5.5.5'
