mode: 'rule'
ipv6: true
bind-address: "*"
geodata-mode: true
geox-url:
  geoip: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"
  geosite: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
  mmdb: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country-without-asn.mmdb"
  asn: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country-asn.mmdb"
geo-auto-update: true
geo-update-interval: 24
profile:
  store-selected: true
  store-fake-ip: true
tun:
  enable: true
  stack: 'gvisor'
  dns-hijack:   
    - 'any:53'
    - 'tcp://any:53'
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
sniffer:
  enable: false
clash-for-android: 
  append-system-dns: true
  ui-subtitle-pattern: ""
dns:
  enable: true
  ipv6: true
  prefer-h3: false
  respect-rules: true
  use-hosts: true
  use-system-hosts: true
  listen: '0.0.0.0:5335'
  enhanced-mode: 'fake-ip'
  fake-ip-range: '198.18.0.1/16'
  fake-ip-filter-mode: 'blacklist'
  fake-ip-filter:
    - 'geosite:cn'
    - 'geosite:steam@cn'
    - 'geosite:category-games@cn'
    - 'geosite:connectivity-check'
    - 'geosite:private'
    - '*.n.n.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
    - 'WORKGROUP'
    - '*.lan'
    - '*.local'
    - 'stun.*.*.*'
    - 'stun.*.*'
    - 'time.windows.com'
    - 'time.nist.gov'
    - 'time.apple.com'
    - 'time.asia.apple.com'
    - '*.ntp.org.cn'
    - '*.openwrt.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'time.ustc.edu.cn'
    - 'pool.ntp.org'
    - 'ntp.ubuntu.com'
    - '*.*.xboxlive.com'
    - 'speedtest.cros.wr.pvp.net'
    - 'ntp.aliyun.com'
    - 'ntp1.aliyun.com'
    - 'ntp2.aliyun.com'
    - 'ntp3.aliyun.com'
    - 'ntp4.aliyun.com'
    - 'ntp5.aliyun.com'
    - 'ntp6.aliyun.com'
    - 'ntp7.aliyun.com'
    - 'time1.aliyun.com'
    - 'time2.aliyun.com'
    - 'time3.aliyun.com'
    - 'time4.aliyun.com'
    - 'time5.aliyun.com'
    - 'time6.aliyun.com'
    - 'time7.aliyun.com'
    - '*.time.edu.cn'
    - 'time1.apple.com'
    - 'time2.apple.com'
    - 'time3.apple.com'
    - 'time4.apple.com'
    - 'time5.apple.com'
    - 'time6.apple.com'
    - 'time7.apple.com'
    - 'time1.google.com'
    - 'time2.google.com'
    - 'time3.google.com'
    - 'time4.google.com'
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - 'music.migu.cn'
    - 'localhost.ptlogin2.qq.com'
    - '*.*.*.srv.nintendo.net'
    - '*.*.stun.playstation.net'
    - '*.ipv6.microsoft.com'
  default-nameserver:
    - '223.6.6.6'
    - '119.28.28.28'
    - '223.5.5.5'
    - '119.29.29.29'
    - '114.114.114.114'
    - '114.114.115.115'
  fallback: null
  nameserver:
    - 'https://223.5.5.5/dns-query'
    - 'https://223.6.6.6/dns-query'
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'
    - "tls://223.5.5.5:853"
    - "tls://223.6.6.6:853"
    - "tls://dot.pub"
    - "tls://dns.alidns.com"
  proxy-server-nameserver:
    - 'https://223.5.5.5/dns-query'
    - 'https://223.6.6.6/dns-query'
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'
    - "tls://223.5.5.5:853"
    - "tls://223.6.6.6:853"
    - "tls://dot.pub"
    - "tls://dns.alidns.com"
  direct-nameserver:
    - '223.6.6.6'
    - '119.28.28.28'
    - '223.5.5.5'
    - '119.29.29.29'
    - '114.114.114.114'
    - '114.114.115.115'
  direct-nameserver-follow-policy: true
  nameserver-policy:
    'software.tongji.edu.cn':
      - '202.120.190.208'
    "geosite:cn":
      - '223.6.6.6'
      - '119.28.28.28'
      - '223.5.5.5'
      - '119.29.29.29'
      - '114.114.114.114'
      - '114.114.115.115'
    "geosite:steam@cn":
      - '223.6.6.6'
      - '119.28.28.28'
      - '223.5.5.5'
      - '119.29.29.29'
      - '114.114.114.114'
      - '114.114.115.115'
    "geosite:category-games@cn":
      - '223.6.6.6'
      - '119.28.28.28'
      - '223.5.5.5'
      - '119.29.29.29'
      - '114.114.114.114'
      - '114.114.115.115'
    '+.claude.ai':
      - 'https://1.1.1.1/dns-query'
      - 'https://8.8.8.8/dns-query'
      - 'tls://1.1.1.1:853'
      - 'tls://8.8.8.8:853'
    '+.claude.com':
      - 'https://1.1.1.1/dns-query'
      - 'https://8.8.8.8/dns-query'
      - 'tls://1.1.1.1:853'
      - 'tls://8.8.8.8:853'
    '+.claudeusercontent.com':
      - 'https://1.1.1.1/dns-query'
      - 'https://8.8.8.8/dns-query'
      - 'tls://1.1.1.1:853'
      - 'tls://8.8.8.8:853'
    '+.claudemcpclient.com':
      - 'https://1.1.1.1/dns-query'
      - 'https://8.8.8.8/dns-query'
      - 'tls://1.1.1.1:853'
      - 'tls://8.8.8.8:853'
    '+.servd-anthropic-website.b-cdn.net':
      - 'https://1.1.1.1/dns-query'
      - 'https://8.8.8.8/dns-query'
      - 'tls://1.1.1.1:853'
      - 'tls://8.8.8.8:853'
    '+.anthropic.com':
      - 'https://1.1.1.1/dns-query'
      - 'https://8.8.8.8/dns-query'
      - 'tls://1.1.1.1:853'
      - 'tls://8.8.8.8:853'
    "geosite:geolocation-!cn":
      - 'https://1.1.1.1/dns-query'
      - 'https://8.8.8.8/dns-query'
      - 'tls://1.1.1.1:853'
      - 'tls://8.8.8.8:853'
    
