tun:
  enable: true
  stack: mixed
  dns-hijack:   
    - 198.18.0.2:5335  # 本地劫持 DNS 地址，无需修改
  auto-route: true
  auto-detect-interface: true
dns:
  enable: true
  listen: '127.0.0.1:5335'
  enhanced-mode: 'fake-ip'
  fake-ip-range: '198.18.0.1/16'
  fake-ip-filter-mode: 'blacklist'
  prefer-h3: false
  respect-rules: true
  use-hosts: true
  use-system-hosts: true
  ipv6: true
  fake-ip-filter:
    - '*.n.n.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
    - 'WORKGROUP'
    - '*.lan'
    - '*.local'
    - 'stun.*.*.*'
    - 'stun.*.*'
    - 'time.windows.com'
    - 'time.nist.gov'
    - 'time.apple.com'
    - 'time.asia.apple.com'
    - '*.ntp.org.cn'
    - '*.openwrt.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'time.ustc.edu.cn'
    - 'pool.ntp.org'
    - 'ntp.ubuntu.com'
    - '*.*.xboxlive.com'
    - 'speedtest.cros.wr.pvp.net'
  default-nameserver:
    - '223.6.6.6'
    - '119.28.28.28'
    - '223.5.5.5'
    - '119.29.29.29'
  nameserver:
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'
  direct-nameserver-follow-policy: true
  fallback-filter:
    geoip: true
    geoip-code: 'CN'
    geosite:
      - gfw
    ipcidr:
      - '240.0.0.0/4'
      - '0.0.0.0/32'
      - '127.0.0.1/8'
    domain:
      - '+.google.com'
      - '+.youtube.com'
      - '+.github.com'
  fallback:
    - 'https://cloudflare-dns.com/dns-query'
    - 'https://dns.google/dns-query'
  proxy-server-nameserver:
    - 'https://doh.pub/dns-query'
    - 'https://dns.alidns.com/dns-query'
  direct-nameserver:
    - '223.6.6.6'
    - '119.28.28.28'
  nameserver-policy:
    '+.tongji.edu.cn':
      - '202.120.190.208'
    '+.126.com':
      - '119.29.29.29'
    '+.126.net':
      - '119.29.29.29'
    '+.127.net':
      - '119.29.29.29'
    '+.163.com':
      - '119.29.29.29'
    '+.alibaba.com':
      - '223.5.5.5'
    '+.alicdn.com':
      - '223.5.5.5'
    '+.alipay.com':
      - '223.5.5.5'
    '+.aliyun.com':
      - '223.5.5.5'
    '+.baidu.com':
      - '223.5.5.5'
    '+.bdstatic.com':
      - '223.5.5.5'
    '+.bilibili.com':
      - '119.29.29.29'
    '+.bilivideo.+':
      - '119.29.29.29'
    '+.douyin.com':
      - '180.184.1.1'
    '+.douyincdn.com':
      - '180.184.1.1'
    '+.douyinpic.com':
      - '180.184.1.1'
    '+.douyinvod.com':
      - '180.184.1.1'
    '+.feishu.cn':
      - '180.184.1.1'
    '+.hdslb.com':
      - '119.29.29.29'
    '+.iqiyi.com':
      - '119.29.29.29'
    '+.jd.com':
      - '119.29.29.29'
    '+.netease.com':
      - '119.29.29.29'
    '+.qpic.cn':
      - '119.29.29.29'
    '+.qq.com':
      - '119.29.29.29'
    '+.taobao.com':
      - '223.5.5.5'
    '+.tencent.com':
      - '119.29.29.29'
    '+.tmall.com':
      - '223.5.5.5'
    '+.weixin.com':
      - '119.29.29.29'
    "+.githubusercontent.com":
      - 'https://cloudflare-dns.com/dns-query'
      - 'https://dns.google/dns-query'
    "+.github.com":
      - 'https://cloudflare-dns.com/dns-query'
      - 'https://dns.google/dns-query'
    "geosite:google":
      - 'https://cloudflare-dns.com/dns-query'
      - 'https://dns.google/dns-query'
    # 自定义直连域名使用国内 dns
    "geosite:cn":
      - 119.29.29.29
      - 223.5.5.5.5
